### ISSUE TITLE
This library fulfills the run-time aspect for practicing EDD

### ISSUE THREAD

**Issue by urbanhop** [danielcrenna/metrics-net#47]
What is EDD ?

**Comment by danielcrenna** [comment]
Experiment Driven Development --- changing software based on its ability to
hit metrics you define in advance.

On Sat, Aug 29, 2015 at 11:54 AM, urbanhop <notifications@github.com> wrote:

> Closed #47 <https://github.com/danielcrenna/metrics-net/issues/47>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielcrenna/metrics-net/issues/47#event-395776751>.
>



-- 
Daniel Crenna
Conatus Creative Inc.
cell:613.400.4286
